default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    #cert_file: "ssl_certs/localhost.crt"
    #cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    handler_search_path:
      - "src/handlers"
    handler_configs:
      LamClient:
        enabled: True
        module: client/h5_rendering_client/client_handler_lam
        asset_path: "lam_samples/barbara.zip"
        concurrent_limit: 5
        turn_config:
          turn_provider: "twilio"
      SileroVad:
        enabled: True
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
      LAM_Driver:
        enabled: True
        module: avatar/lam/avatar_handler_lam_audio2expression
        model_name: ""
        feature_extractor_model_name: "facebook/wav2vec2-base-960h"
        audio_sample_rate: 24000
